### ISSUE TITLE
Support syntax highlighting

### ISSUE THREAD

**Issue by jaspervdj** [jaspervdj/patat#10]
Pandoc uses `highlighting-kate` to do syntax highlighting.  We could leverage this as well.  `highlighting-kate` produces HTML which is very easy to parse -- it just contains a number of elements for different tokens, in a `<code>` block.  We can parse this HTML and convert it to colored terminal output.

**Comment by nbrandaleone** [comment]
An example would be helpful.

**Comment by jaspervdj** [comment]
Hi @nbrandaleone; syntax highlighting is enabled by default.  It works similar to syntax highlighting on GitHub, just tag the right language, e.g.:

    ```ruby
    puts "Hello, world"
    ```

I'll add this to the README as well.
