### ISSUE TITLE
image support for Kitty terminal?

### ISSUE THREAD

**Issue by haoyun** [jaspervdj/patat#100]
The kitty terminal is able to display images natively. Will that be supported?

https://sw.kovidgoyal.net/kitty/kittens/icat.html

**Comment by jaspervdj** [comment]
Thanks for the suggestion!  The next version will support this.

**Comment by jaspervdj** [comment]
This and #101 should be fixed in [v0.8.7.0](https://github.com/jaspervdj/patat/releases/tag/v0.8.7.0).

**Comment by laoshaw** [comment]
I'm using patat 0.8.7.0 and it did not show images, mdcat shows up the image from markdown file just fine

test.md:

```
## test img inside kitty

![](linux.jpg)
```

![linux](https://user-images.githubusercontent.com/18351761/141693421-412d8e3c-4bcf-451c-990f-3ad6900dcb8f.jpg)

mdcat test.md:

![xx](https://user-images.githubusercontent.com/18351761/141693462-9cab6d4c-1342-44be-9177-44e9117e93b5.png)

patat test.md

![yy](https://user-images.githubusercontent.com/18351761/141693470-d7e780dc-27d0-4993-8817-06e603d1a1f0.png)

**Comment by jaspervdj** [comment]
@laoshaw Do you have the following YAML metadata present?  You need to enable this feature, it's not on by default.

```
---
patat:
  images:
    backend: auto
...

## test img inside kitty

![](linux.jpg)
```

**Comment by laoshaw** [comment]
I have this in my $HOME/.patat.yaml

```
---
patat:
  images:
    backend: auto
...
```

replaces auto with 'kitty' (as I have w3mimg installed too), to no help.
