### ISSUE TITLE
authorWidth (in footer) for author name with CJK characters

### ISSUE THREAD

**Issue by haoyun** [jaspervdj/patat#101]
I tried to set author with CJK characters, then the footer is incorrectly displayed. The problem seems to be L93:

https://github.com/jaspervdj/patat/blob/891dc4971ad1a00b3833ca6a848151a7c921f9da/lib/Patat/Presentation/Display.hs#L90-L94

a fullwidth CJK character should have double the width of a latin character.

**Comment by jaspervdj** [comment]
Thanks a lot for reporting this!  Should be fixed in the next release.
