### ISSUE TITLE
eval block doesn't work for some commands

### ISSUE THREAD

**Issue by cskksdfklpz** [jaspervdj/patat#104]
First of all I very like this project. It's really cool.

However, when I was trying the eval block, I found that some commands like `cat`, `head` doesn't work. I also tried `ls`, `pwd` and they worked, so I'm not sure what makes the former two commands different. Do I need to make some additional configurations?

```markdown
---
title: Title
author: Author
patat:
   eval:
        tail:
            command: tail
...
```tail
./presentation-patat.md
```
```


what I've got:

```bash
                                       Title


    ./presentation-patat.md



    ./presentation-patat.md




```

**Comment by jaspervdj** [comment]
@cskksdfklpz Thanks for reporting!  I assume the issue with these commands is that they wait to read all of `stdin`?  If you just type `tail` in your terminal, it doesn't terminate either, until you do ctrl+d or ctrl+c or similar.

**Comment by cskksdfklpz** [comment]
So how can we solve this issue? Should I add some termination command at the end of the command?

**Comment by jaspervdj** [comment]
You can do something like: `timeout 10s <other command>`; or close stdin with `echo | cat`.  I will close this issue since this is really more about Unix rather than patat; but feel free to add more comments if you have follow-up questions.
