### ISSUE TITLE
Adding another library for syntax highlighting.

### ISSUE THREAD

**Issue by redvers** [jaspervdj/patat#105]
Greetings, I'm trying to build some slides around the pony language but alas the package on hackage doesn't seem to have that language support.

It's in the kate database so I have the xml file.

My question really is how would I go about adding it?

(Note: if I call pandoc directly at the command-line like so:

```pandoc foo.md --syntax-definition pony.xml``` is sufficient for the resultant html to be marked up correctly (wrong workflow I know - but useful to know that my .xml definition is good).

Thanks!

Red

**Comment by jaspervdj** [comment]
Hi @redvers!  There is a bit of a long dependency chain here:

- Patat depends on Pandoc for parsing;
- Pandoc depends on Skylighting for hightlighting;
- Skylighting in turn pulls in the XML files from Kate.

It seems like the last Skylighting update was around 6 months ago.  I assume that Pony will be included in the next release.  However, that may still take a while.  Alternatively, I can see if we can add a similar `--syntax-definition` flag to patat?

**Comment by redvers** [comment]
That would be amazing if you could ... I traced the dependencies down and I don't see how patat integrates with pandoc specifically.

I was chewing through the documentation and even tried to strace patat to see if I could see where it was pulling the ruby syntax from - even if I just swap out the files temporarily to get me moving :-)

(Obviously that's not a proper fix - but my presentation is in about a week so I'm resorting to hackery of the worst kind) :-)

**Comment by klarkc** [comment]
@jaspervdj the same way I am trying to syntax highlight PureScript, the [xml is there](https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/purescript.xml) , with v0.8.7.0, but it does not work. The file were added Jul 15, 2020, the skylighting-core in stack lock file is 0.13 (which is the latest one from 30 Jul 2022), so it seems that skylighting-core is being updated without pulling all files in KDE's repo

**Comment by jaspervdj** [comment]
@klarkc Yeah, it seems like PureScript is not there yet... maybe you can file a PR against skylighting to add it from the KDE repos?  I'm tempted to work on an extra syntax highlighting flag at some point, but I'm not sure if it will be soon.

**Comment by klarkc** [comment]
Added jgm/skylighting#158
