### ISSUE TITLE
Speaker notes?

### ISSUE THREAD

**Issue by isovector** [jaspervdj/patat#106]
Patat is excellent, though I often find myself wanting to add speaker notes when building my slide deck. Is there any official (or even unofficial) support for such a thing?

**Comment by jaspervdj** [comment]
Hey @isovector!

My approach to this is to add HTML comments in the presentation like this:

```
---
title: This is my presentation
author: Jane Doe
...

# Chapter 1

<!--
Note: I should not bore the audience with my thoughts on powerpoint but
just get straight to the point.
-->

Slide contents.  Yay.

<!-- TODO: Finish the rest of the presentation. -->
```

Obviously this does not work with doing more advanced things such as showing the notes separately on a second screen, but I just use a second text editor window I scroll manually.  I'm not sure if this is a satisfactory answer -- I'm not sure if I want to do the full second thing view as it would really increase the complexity of patat and I like to keep things simple :-)

**Comment by isovector** [comment]
Thanks @jaspervdj . This was exactly what I had in mind by "unofficial" support. Cheers! See you in a few days!

**Comment by kalidasya** [comment]
Is it possible to make it work with list items without adding extra newlines to the list?

**Comment by jaspervdj** [comment]
To follow up on this, I figured out how to display notes in a second window without over-complicating things: #142.
