### ISSUE TITLE
Per slide or per fragment background color

### ISSUE THREAD

**Issue by Kabouik** [jaspervdj/patat#107]
It would be pretty nice to be able to set the background color, as this can be used to emphasize on some things or distinguish parts of a talk. [`present`](https://github.com/vinayak-mehta/present) for instances has this feature (and some others, like effects), but it is missing full image support (among other things) so `present` and `patat` are not really interchangeable.

**Comment by jaspervdj** [comment]
Thanks for reporting!  Looks like present uses this syntax on the first line of a slide:

```
<!-- fg=black bg=yellow -->
```

This seems compatible with what syntax patat uses right now, as we already ignore HTML comments.  I'll see if I can hack on it a bit during ZuriHac.

**Comment by Kabouik** [comment]
Nice, I hope your attempts will be conclusive.

Do you foresee it would be technically possible to extend that to fragments, or maybe to make the background a fragment itself? I am new to `patat` but I assume fragments are limited (I think fragments can only be shown, not hidden, or shown then hidden, and they have to can only appear from top to bottom of the text body), so perhaps this would imply more profound changes on fragments and would be a totally different task.

**Comment by jaspervdj** [comment]
I did part of this in #148, which adds a per-slide configuration.  The background color isn't customizable but that can be tackled separately.
