### ISSUE TITLE
Hide page number

### ISSUE THREAD

**Issue by iliocatallo** [jaspervdj/patat#112]
Hello there,

I was wondering if there is a way to hide the page number (maybe via a configuration). For the time being, I just removed `active` from the concatenation at https://github.com/jaspervdj/patat/blob/1c72d3b059fde7e6a17d466afbaf2490e424f5b5/lib/Patat/Presentation/Display.hs#L73 and recompiled.

Thank you, ciao!

**Comment by jaspervdj** [comment]
Hi @iliocatallo, this currently isn't possible but I'm open to adding this as a configuration setting.  Is this something you would want to create a PR for?  I think it should just be a matter of adding this to `PresentationSettings` and then removing it from the concatenation as you suggested.

**Comment by iliocatallo** [comment]
Hi @jaspervdj,

Sorry for the late reply. Haskell is not my day-to-day language, but I can try to give it a look. 

ciao!
