### ISSUE TITLE
[REQUEST] describe usage of pandoc

### ISSUE THREAD

**Issue by nkh** [jaspervdj/patat#114]
Hi, looks like a great application and the screenshot is what I would like to achieve to preview MD on the terminal.

Could you please explain how to get that result on the command line or if possible render a whole MD, without slides, to stdout or a file?

**Comment by jaspervdj** [comment]
@nkh You can use `patat --dump slides.md` to dump everything in one go.

But-- I mostly built this so I can test the patat output against expected files automatically, not to preview MD.  So it may not fully work for your use case.

If there's any changes that can be made to `--dump` so it works for your use case, let me know.
