### ISSUE TITLE
does not compile anymore with lts-6.22

### ISSUE THREAD

**Issue by legrostdg** [jaspervdj/patat#12]
/home/user/src/patat/src/Patat/Theme.hs:258:5:
        Non type-variable argument
          in the constraint: Data.String.IsString [a]
       (Use FlexibleContexts to permit this)
        When checking that ‘dropTok’ has the inferred type
          dropTok :: forall a. (Eq a, Data.String.IsString [a]) => [a] -> [a]
        In an equation for ‘nameForTokenType’:
            nameForTokenType
              = unCapitalize . dropTok . show
              where
                  unCapitalize (x : xs) = toLower x : xs
                  unCapitalize xs = xs
                  dropTok str
                    | "Tok" `isSuffixOf` str = take (length str - 3) str
                    | otherwise = str

**Comment by jaspervdj** [comment]
Released as `v0.3.1.0`.  Thanks for the patch!
