### ISSUE TITLE
Real-time output of long-running commands in patat

### ISSUE THREAD

**Issue by stark71** [jaspervdj/patat#132]
When evaluating long-running commands in patat, the slide remains unresponsive until the command is finished. This can be an issue when giving presentations as it can interrupt the flow of the talk. It would be helpful to have a way to display the output of the command in real-time, so the audience can see progress as it is made.

This is particularly important for commands that write log lines to stdout every few seconds, as it would be useful to see those lines as they are received by patat.

A desirable addition to the patat eval configuration would be the inclusion of a timeout parameter.

**Comment by jaspervdj** [comment]
This should be fixed in #173, released in `v0.13.0.0`.
