### ISSUE TITLE
display errors and keep running

### ISSUE THREAD

**Issue by simonmichael** [jaspervdj/patat#14]
It's easy to kill `patat --watch`, eg when tweaking yaml metadata, which breaks the flow:
```
Error parsing patat settings from metadata: failed to parse field theme: When parsing the constructor Theme of type Patat.Theme.Theme expected Object but got String.
```
It will be nice to catch these and keep running, displaying the error until fixed.

Thanks for this neat tool!

**Comment by jaspervdj** [comment]
Thanks for reporting.  I released this fix as `v0.3.2.0`.
