### ISSUE TITLE
more control of slide splitting with deep outlines

### ISSUE THREAD

**Issue by simonmichael** [jaspervdj/patat#16]
Encouraged by your swift feature request response (thank you) I have more! :)

I've switched to using an org file as the source. This will work really nicely for sketching out a presentation. I started grouping slides into sections. But currently patat puts everything below each top-level org node into a single slide. I was wanting one slide for each node and its immediate content, for all nodes in depth-first order. 

pandoc has a `--slide-level` option, supporting this might be part of the solution. Eg with `--slide-level 2`, pandoc makes a slide for each first and second-level node. (It has a problem too, nodes above the specified depth create only empty slides, their content is ignored.)

<s>I can imagine some more configurations, where sometimes you want slides to inline one or more levels of sub-nodes (`--slide-sublevels` ?) but that seems to get a bit complicated and I don't have a clear specification yet.</s>

I guess patat has its own slide-splitting logic and is not relying on pandoc's. Ideally it would work similarly in both tools.

**Comment by jaspervdj** [comment]
I would like `patat` to mirror's pandoc slide-splitting logic (but with a default slide-level of 1).  This can hopefully go in the next release.

**Comment by t184256** [comment]
> (but with a default slide-level of 1)

I disagree. The default should mirror pandoc's autodetection, defined as

> By default, the slide level is the highest header level in the hierarchy that is followed immediately by content, and not another header, somewhere in the document.

**Comment by jaspervdj** [comment]
Hey @simonmichael -- do you want to give the code in PR #32 a try and see if you have any feedback?  If it's good it can go in the next release of `patat`.

**Comment by jaspervdj** [comment]
Fixed in `patat-0.5.0.0`.

**Comment by simonmichael** [comment]
Sorry @jaspervdj, I didn't get around to it. Will check it out next time, thank you.

**Comment by simonmichael** [comment]
Sorry @jaspervdj, I didn't get around to it. Will check it out next time I use, thank you.

**Comment by jaspervdj** [comment]
No worries, it was a great improvement to suggest.
