### ISSUE TITLE
save to one of pandoc's slides formats also ?

### ISSUE THREAD

**Issue by simonmichael** [jaspervdj/patat#17]
I want images in the current presentation so I switch to one of pandoc's other slide formats (`pandoc talk.org -t s5 -o talk.s5.html`). I miss patat's lovely --watch feature. I can leave it running in another window, but patat's and pandoc's slide splitting is different (#16 can help with this). I can script pandoc to reconvert on save, and the browser to reload on change (livereloadx), but it's a hassle and it doesn't keep showing the same slide. 

I wondered if it would be a good option to also save to a richer format, eg: `patat --watch talk.org --save-to s5` would update talk.s5.html as well as the terminal display. Ie, patat would be serving as a pandoc auto-runner and also handy quick previewer. But reloading the current slide in the browser is still unsolved, and maybe all of this is out of scope.

**Comment by jaspervdj** [comment]
I don't think this is in scope for `patat`, sorry.
