### ISSUE TITLE
multibyte characters create codeblocks rendering issues

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [jaspervdj/patat#171]
given the following input

    ---
    patat:
      margins:
        left: 4
        right: 10
        top: 3
      theme:
        codeBlock: [ vividGreen,onRgb#101010 ]
    ...
    
    # what am i running?

    add to `$PS1`:
    ```
    🐘 $(php -v | grep "^PHP" | cut -d " " -f2)
    ```

i'll end up with a misaligned codeclock

![image](https://github.com/user-attachments/assets/4019d14b-7147-46c5-b585-98cc20f66c27)

**Comment by jaspervdj** [comment]
Thanks for reporting the issue!  I have fixed this in `main` and will release this as `v0.12.0.1`.

**Comment by jaspervdj** [comment]
This fix has been included in [v0.12.0.1](https://github.com/jaspervdj/patat/releases/tag/v0.12.0.1)
