### ISSUE TITLE
tab character create codeblocks rendering issues

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [jaspervdj/patat#172]
having a `\t` in a codeblock will throw the codeblock rendering off

a bit hard to inline, so here is a link to the slide in question: https://github.com/verfriemelt-dot-org/slides/blob/main/faster/parts/55-makefile/10-makefiles.md

![image](https://github.com/user-attachments/assets/5ae9e760-3143-45fd-9b92-2a89cf81656a)

**Comment by jaspervdj** [comment]
Thanks for reporting!  I couldn't reproduce it on the first try:

![image](https://github.com/user-attachments/assets/bee1b020-6d55-4901-bb20-23119084c1ac)

Could you check which of version of patat you are running (`patat --version`) and see if you have any configuration that is not in the slide (e.g. in `~/.config/patat/config.yaml`)?

**Comment by verfriemelt-dot-org** [comment]
argh, sorry. i checked my slides using my demo user which uses the system default and not the `$HOME/bin` version.
debin sid packages still patat 0.11.0.0 - with version 0.12.0.1 its working as expecpted

https://packages.debian.org/unstable/patat
