### ISSUE TITLE
Support for slide splitting/pause/fragments

### ISSUE THREAD

**Issue by mrshu** [jaspervdj/patat#18]
Let me start by saying thanks a ton @jaspervdj for `patat`! I just delivered a talk for which I prepared `patat` slides in Markdown. The whole experience was quite pleasant and I did enjoy both the preparation and the actual presentation.

The only thing I was really missing was the ability to 'split the slide' (something like [fragments in reveal.js](https://github.com/hakimel/reveal.js/#fragments) or the [`+` in vroom](https://github.com/ingydotnet/vroom-pm#input-format)). I was kind of forced to manually repeat contents of the previous slide if I wanted something like the features I listed above.

I am not sure if this would be possible in the current setup of `patat`, but in the worst case, I believe the manual process of copying the slide contents over can be automated, so I believe that there might be at least a 'hacky' way of doing this.

Thanks again!

**Comment by jaspervdj** [comment]
Thanks for the kind comments!

I would also like to have this in `patat`.  It's not super hard to implement -- the hardest part is choosing the correct syntax.

I can't really go with something generic as `+`.  I need go with a semantic element that is supported in (almost) all input formats.  You see, the slides are only split after Pandoc parses the document.  That means we need to recognize the "fragment" _in_ Pandoc's parsed AST.

E.g. for splitting slides we use `\hrulefill` in LaTeX or `---` in Markdown.

What do you think of using a link to `#fragment` as a splitter?  Creating a link should be supported in all input formats.  The fact that this is an inline element is also nice.

```
- This is [](#fragment)
- a split-up [](#fragment)
- list.
```

**Comment by mrshu** [comment]
@jaspervdj Sorry for my late response.

I really like the idea of using `[](#fragment)` -- it is not very intrusive and at the same time quite cross-compatible. I had to check whether LaTeX would have an appropriate alternative for a link, but it seems that there is at least one.

I would gladly help with implementing this, but my knowledge of both Haskell and Pandoc internals is quite rudimentary.

**Comment by jaspervdj** [comment]
@mrshu I have added support for this.  I decided to implement it slightly differently than outlined here.

The README has a description of how it works: <https://github.com/jaspervdj/patat#fragmented-slides>.

This will go into the next release together with some other things.

**Comment by mrshu** [comment]
Thanks @jaspervdj, I actually like your implementation more than the proposal in this task.

Kudos for putting it together!
