### ISSUE TITLE
add a manpage

### ISSUE THREAD

**Issue by legrostdg** [jaspervdj/patat#19]
Would you consider adding a manpage?

**Comment by jaspervdj** [comment]
Yes, I would like to have that.  I added some initial stuff in `feature/add-man-page` branch.

**Comment by jaspervdj** [comment]
I wasn't able to add a man page in the current release but one of the goals for the next release is to set up some sort of script that generates the man page from the README.

**Comment by jaspervdj** [comment]
This has been done in `0.4.2.0`.  `make man` builds the man page to `extra/patat.1`.
