### ISSUE TITLE
add to stackage

### ISSUE THREAD

**Issue by legrostdg** [jaspervdj/patat#21]
Would you consider adding patat to stackage?

**Comment by jaspervdj** [comment]
Yes, but `pandoc` is currently not in Stackage because of a dependency problem.  Once it's added again, I will add `patat` as well.

**Comment by legrostdg** [comment]
Maybe the pull request could be added, with an indication that it is blocked by pandoc reentering stackage? (So that it is not forgotten)

**Comment by jaspervdj** [comment]
Good idea.  I have done that [here](https://github.com/fpco/stackage/pull/2020).

**Comment by legrostdg** [comment]
Should be added now https://github.com/fpco/stackage/pull/2035
