### ISSUE TITLE
Support for slide duration

### ISSUE THREAD

**Issue by Kraymer** [jaspervdj/patat#23]
I intend to use patat as a way to comment my actions when recording asciicasts (by having patat running in a tmux panel).
For that purpose, it would be useful to have the slide automatically switching to the next after a specified delay.
 
    ---
    patat:
          duration: 10
    ...

**Comment by jaspervdj** [comment]
Yes, sounds pretty reasonable.  I would call the setting `autoNextSlide`.  It needs to be a bit smart in setting timeouts, e.g., when the user presses a key we need to reset it.

**Comment by jaspervdj** [comment]
@Kraymer I have added support for this in the `master` branch.  See <https://github.com/jaspervdj/patat#auto-advancing> for more info.  This will go into the next release.
