### ISSUE TITLE
getting date from git when generating the manpage is an issue for Debian packaging

### ISSUE THREAD

**Issue by legrostdg** [jaspervdj/patat#26]
Debian package system builds from a tarball, so it can't get the date from git when generating the manpage... Would it be possible to get this date from SOURCE_DATE_EPOCH, set for this purpose?

**Comment by jaspervdj-luminal** [comment]
Yeah that sounds good.  I saw a talk about reproducible builds in Debian at FOSDEM and really liked it.  I'll fall back to git if `SOURCE_DATE_EPOCH` is undefined.

**Comment by legrostdg** [comment]
great!

**Comment by jaspervdj** [comment]
I've fixed this in `patat-0.4.3.0`.  Let me know if it doesn't work for some reason.

**Comment by legrostdg** [comment]
It seems like `patat` build still is unreproducible... https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/diffoscope-results/patat.html

**Comment by jaspervdj-luminal** [comment]
Any idea how this happened?  Where two different `SOURCE_DATE_EPOCH`s passed?

**Comment by legrostdg** [comment]
No idea... I guess that's not the problem, as it would defeat the purpose of `SOURCE_DATE_EPOCH`.

It is linked to this issue: https://tests.reproducible-builds.org/debian/issues/unstable/timestamps_in_documentation_generated_by_pandoc_issue.html
