### ISSUE TITLE
reproducible build: locale

### ISSUE THREAD

**Issue by legrostdg** [jaspervdj/patat#28]
Patch provided by Daniel Shahaf <danielsh@apache.org>:

Hi!

While working on the “reproducible builds” effort [1], we have noticed
that patat could not be built reproducibly.

While it already uses $SOURCE_DATE_EPOCH, it renders that date in
a locale-dependent manner.

Patch attached.

Thanks,

Daniel

    diff --git a/Makefile b/Makefile
    index 5ca60d4..68c36b4 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -9,7 +9,7 @@ SOURCE_DATE_EPOCH?=$(shell date '+%s' \
                                               --date="$(shell git log -1 --format=%cd --date=rfc)")
    
     # Prettify the date.
    -SOURCE_DATE=$(shell date '+%B %d, %Y' -d "@${SOURCE_DATE_EPOCH}")
    +SOURCE_DATE=$(shell env LC_ALL=C date '+%B %d, %Y' -d "@${SOURCE_DATE_EPOCH}")
    
     extra/patat.1: README.md extra/make-man
            SOURCE_DATE="$(SOURCE_DATE)" ./extra/make-man >$@

**Comment by jaspervdj** [comment]
Thanks for relaying this.  I've applied this patch in `patat-0.4.5.0`.
