### ISSUE TITLE
Remove cursor / bottom line

### ISSUE THREAD

**Issue by amerlyq** [jaspervdj/patat#29]
Would it be possible to place cursor on line *before* the bottom-most, and make cursor *invisible* instead?
Of course, disabling `echo` to keep footer intact from overriding by incidental typing.
It's easy for ncurses, but maybe there are some reasons why it haven't been done for `patat`?
I make fullscreen presentation with many code snippets from `gdb` and even that single line is essential for me :)

**Comment by jaspervdj** [comment]
The improvements are now on the `master` branch.  Thanks for the suggestions!

**Comment by amerlyq** [comment]
Update had come right before I hold the meeting.
Thanks, it was impressively fast :)
