### ISSUE TITLE
Improve link pretty printing

### ISSUE THREAD

**Issue by PierreR** [jaspervdj/patat#3]
Links appears at the end of slides:

![patat](https://cloud.githubusercontent.com/assets/93115/19148488/40565aec-8bbd-11e6-96c1-79510b3ca6aa.PNG)

This makes the presentation looks clumsy (and more difficult to read from) IMHO.

**Comment by jaspervdj** [comment]
To be honest, I putting links at the end of slides feels neater to me personally.  Links in this form are already inlined: `An <http://example.com/> site`.

I would be open to having this configurable though.

I'm currently dabbling with the idea of providing configuration through the Pandoc metadata block at the start of the file (possible in addition to a `~/.config/patat/settings.yaml`, the per-file settings would override the global ones).

**Comment by PierreR** [comment]
Thanks for the info. By the way, `inlined
![patat2](https://cloud.githubusercontent.com/assets/93115/19155821/22f65812-8be0-11e6-9aa7-3295fcc09e7b.PNG)
 links` are not cyan. Is that intended ?

**Comment by jaspervdj** [comment]
Is the inline link wrapped in `<>`?  If not, that's not "standard" markdown (I realize "standard" is super dubious here).

**Comment by dosmanak** [comment]
Hello. How this issue is completed?
I write my presentation using links with reference-style so all links are at the end of the document.
I'd like to have all links on separate slide at the end of presenation.

**Comment by jaspervdj** [comment]
@dosmanak can you open a new issue for that?  We can discuss what the configuration for having links on a separate slide should look like there.
