### ISSUE TITLE
Changing `autoAdvanceDelay`is ignored in `--watch` mode

### ISSUE THREAD

**Issue by kakty3** [jaspervdj/patat#31]
Consider presentation file with `autoAdvanceDelay: *`. Run patat with `-w` flag.
Removing `autoAdvanceDelay` of changing its value does nothing – `autoAdvanceDelay` will stay the same.

**Comment by jaspervdj** [comment]
I am aware of this but not sure if it is worth fixing -- it would significantly complicate the `autoAdvance` code and I don't really see why this would be very useful.  I would prefer to just add a snippet to the documentation on how this works (unless you have a really compelling use case).

**Comment by kakty3** [comment]
Sure, adding note to documentation will be enough.
