### ISSUE TITLE
Improve help about theming presentation

### ISSUE THREAD

**Issue by PierreR** [jaspervdj/patat#4]
It would be nice to add some guidance about how to theme a presentation. 

For instance `highlights`  or `code snippets` on a lightweight background have currently a black background. Is this intended ? Would you advice to go with a dark background.

Some little pointers about how to make the presentation looks good (even if there is only one theme) would be helpful.

Thanks.

**Comment by jaspervdj** [comment]
For the current prototype, I based everything on what looks good in the dark [solarized](http://ethanschoonover.com/solarized) theme.  I would like to add simple theming support though -- not necessarily through theme files but just settings you can tweak in the configuration.

**Comment by jaspervdj** [comment]
You can now change these settings in the configuration.  See: <https://github.com/jaspervdj/patat#configuration>.
