### ISSUE TITLE
add a new release (supporting ansi-terminal >= 0.8)

### ISSUE THREAD

**Issue by legrostdg** [jaspervdj/patat#46]
It would be nice to be able to build patat with ansi-terminal >= 0.8. The version currently in stackage (and Debian, thus preventing the updating of the package) is 0.8.0.2.  The same version is the one available on Debian sid, which was updated to lts-10/ghc8.2.2 recently. As a nice bonus, it would be great to add patat back to stackage, to be able to notice build problems with new library versions.

**Comment by legrostdg** [comment]
Woops, I did not see it was already implemented on master... Would you mind pushing a new release?

**Comment by jaspervdj** [comment]
Released as `patat-0.6.1.1`

**Comment by legrostdg** [comment]
Thanks! In the meantime `pandoc` was updated to 2.2 in debian unstable... Could you update this and push a new release?

**Comment by jaspervdj** [comment]
Done as well, in `patat-0.6.1.2`.

**Comment by legrostdg** [comment]
Thanks! I uploaded the new patat to debian unstable.
