### ISSUE TITLE
How can I use non-Markdown formats?

### ISSUE THREAD

**Issue by jaccarmac** [jaspervdj/patat#5]
Stumbled across the project on HN this morning and played with a couple Markdown presentations. Super slick for those, but invoking on an Org mode file failed with a message about unknown file types. According to the [README](https://github.com/jaspervdj/patat/tree/235bff9d11cfb9ba5b506de4250c4002bace5a2a#input-format), Org should work if it's supported by Pandoc (it is). Is there a subset of formats which can be presented, work to be done, some combination of both? Let me know!

(Tangentially related, this finally got me to install Stack and could be a good excuse to start learning real Haskell if there's a contribution necessary somewhere.)

**Comment by jaspervdj** [comment]
You can submit a patch here:

<https://github.com/jaspervdj/patat/blob/master/src/Patat/Presentation/Read.hs>

As you can see, `.org` is already in there but I haven't made a release yet (writing this from mobile).

**Comment by jaccarmac** [comment]
Neat, thanks!
