### ISSUE TITLE
Request: more code examples

### ISSUE THREAD

**Issue by jjant** [jaspervdj/patat#55]
Hey there! I've been trying patat and it's great. I was confused for a while on how to do presentations with embedded code/lhs, could you add a few more examples? Perhaps showing how to get what's in the screenshot in your readme. Thanks!!

Separate question, is it possible to eval code? I.e, have some lhs get evaluated when pressing next slide. Thanks again!

**Comment by jaspervdj** [comment]
Hi @jjant, here a few more examples of talks I've given using `patat`:

- https://github.com/jaspervdj/talks/blob/master/2016-cufp-ludwig/slides.md
- https://github.com/jaspervdj/talks/blob/master/2017-haskell-exchange-getting-things-done/slides.md
- https://github.com/jaspervdj/talks/blob/master/2017-skillsmatter-errors/slides.md
- https://github.com/jaspervdj/talks/blob/master/2017-uofmd-practical-haskell/slides.md
- https://github.com/jaspervdj/talks/blob/master/2018-haskell-exchange-binomial-heap/slides.lhs
- https://github.com/jaspervdj/talks/blob/master/2018-haskell-exchange-patat/slides.md

There is another open issue about integrating with the output of tools #52 but I haven't been able to spend much time on that.  I usually switch in between the presentation and GHCi for now.  Please contribute any ideas you might have to the other issue :-)
