### ISSUE TITLE
No italic output

### ISSUE THREAD

**Issue by oblitum** [jaspervdj/patat#57]
My terminal emulator (termite) supports italic text, and it works fine, but `patat` doesn't output italic, it just change color for text that's marked for italic. Also, bold text changes color to red, beyond correctly assigning bold output, I dunno why the red color, it doesn't make much sense for me.

**Comment by jaspervdj** [comment]
Thanks for the report!  I think italics (and bold, for that matter) are generally not well supported in terminals.  However, as I read your issue I realized it currently isn't possible to do italics _at all_ which definitely pretty bad.

I've fixed this in #58 which I releases as `patat-0.8.1.1`.  The following settings should work there:

```markdown
---
patat:
  theme:
    emph: [italic]
    strong: [bold]
...

# This is a slide

**Strong** and _emph_.
```

Please let me know if this doesn't work!

**Comment by oblitum** [comment]
Hi thanks, I'll have to wait for an AUR release, because I don't have a Haskell setup. I didn't get your report very well, do you mean it will not be enabled by default, because it won't work for everybody, but that you provided a setting that I can use to have it enabled? It sounded a bit that it won't work at all, but try this.

**Comment by jaspervdj** [comment]
Yes; it means that it will not be enabled by default, but if you use the presentation above (with the `theme` setting), it should work fine.

I've updated the `patat-bin` package in AUR to `v0.8.1.1` as well.

**Comment by oblitum** [comment]
Thanks!, it's working great.
