### ISSUE TITLE
No image support (`imgcat`)

### ISSUE THREAD

**Issue by piotr-yuxuan** [jaspervdj/patat#6]
Hi, thanks a lot for this super-hype geek tool :-)
Just a little PR to let you know it would be ever more awesome to take advantage of `imgcat` and display pictures.
No offense if you close this PR, I'd understand ^^

**Comment by jaspervdj** [comment]
This sounds good to me as long as it stays working nicely in other terminals and it is opt-in.

It would be cool to implement this using [JuicyPixels](https://hackage.haskell.org/package/JuicyPixels) to do resizing and then convert it to iTerm2's proprietary protocol.

**Comment by lwm** [comment]
:rocket:

**Comment by piotr-yuxuan** [comment]
Wait, did you just say _<quote>proprietary</quote>_? :-/ At least it's described.

**Comment by jaspervdj** [comment]
@piotr-yuxuan Sorry, I meant non-standard.

**Comment by jaspervdj** [comment]
This is fixed in #50
