### ISSUE TITLE
RPM Package

### ISSUE THREAD

**Issue by bramceulemans** [jaspervdj/patat#72]
Hello, would it be possible to also build an RPM package for Fedora/RHEL?

Now I have to install Stack just for Patat :')

**Comment by jaspervdj** [comment]
Hi @BramCeulemans, I don't use Fedora/RHEL so I'm not sure if I want to take on the burden of maintaining an RPM.  Does the [binary release](https://github.com/jaspervdj/patat/releases) of patat  work on your platform?

**Comment by BramCeulemans** [comment]
Yes, the binary release works just fine. If you want I can take a look into making an RPM package?

**Comment by jaspervdj** [comment]
That would be most welcome!  Let me know if there's anything I can do from my side to help.

**Comment by larsks** [comment]
patat is already packaged in Fedora (F31 has 0.8.2.3). You can just:

```
yum install patat
```

Package sources are at https://src.fedoraproject.org/rpms/patat.

**Comment by jaspervdj** [comment]
That's awesome, thanks for the heads up @larsks!  Let's leave this issue open as a reminder for me to add this to the README.
