### ISSUE TITLE
Binaries for Mac OS

### ISSUE THREAD

**Issue by kodaman2** [jaspervdj/patat#82]
I have built the binary for Mac OSX I am using Mojave, I don't use much Haskell or the stack for that matter and the whole build setup with `stack install` took a while around 30+ and took a few GBs in space. Might help for others interested in the project by trying it out first.

Would you like for me to send you the executable for mac?
And does pandoc gets built in the executable?

I couldn't find pandoc installed on the system reason why I am asking. `pandoc --version` returns nothing, but patat is working great with markdown files.

``` patat --version
0.8.4.1
Using pandoc: 2.7.3
```

**Comment by jaspervdj** [comment]
This is awesome!  Sorry for the late reply.

Yes, I think having to compile the project is a huge barrier for Mac users and this would solve that.  Feel free to send me the binary.  I will need to mark it as "unofficial" though, as I have no way of knowing if the source was not patched.

Patat uses pandoc as a library, so the pandoc binary typically doesn't get built unless you explicitly ask for it.

An alternative to this would be to add patat to homebrew, but I don't really have experience with that either.

**Comment by kodaman2** [comment]
I could setup an Azure Devops project if you'd like. Can automatically build releases for multiple OSes. That would be a more official way, and efficient way. 

Shoot me an email fredz0003@gmail.com

**Comment by jaspervdj** [comment]
Let me see if it's possible to get CircleCI to do it, so I can reuse the current infra.  If it doesn't work; I'll reach out to you (and I may reach out anyway to test the binary).

**Comment by kodaman2** [comment]
Ok cool. I tried a quick linux build on azure devops. And it does take about the same time because it downloads everything on each build about 30min. Though the build was huge 100MB not sure why. Ideally is better to use a same agent so builds are quicker but hey as long as a commit triggers the build who cares how long it takes.

Yeah I'll be glad to test mac binaries.

**Comment by jaspervdj** [comment]
Hi @kodaman2, I set up Mac OS builds on Circle in #83.  Are you able to test the binary that was produced here?  https://github.com/jaspervdj/patat/releases/tag/v0.8.4.2

**Comment by kodaman2** [comment]
> Hi @kodaman2, I set up Mac OS builds on Circle in #83. Are you able to test the binary that was produced here? https://github.com/jaspervdj/patat/releases/tag/v0.8.4.2

Tested on Mojave 10.14.5 successfully. Awesome work! I will make the repo where I had what I compiled private now since is not needed anymore.
