### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by NightMachinary** [jaspervdj/patat#87]
This will make installing and updating it on macOS a lot easier. I personally use homebrew on Linux, too, as it offers up-to-date versions compared to default repositories.

**Comment by jaspervdj** [comment]
I would love to have this, but I don't have any experience with Homebrew.  Would you be willing to contribute this?  I'm happy to help out with any issues or changes you need from the patat / haskell side.

**Comment by NightMachinary** [comment]
@jaspervdj I don't have any experiences writing a brew formula either, unfortunately. Also, I think the brew maintainer should be a common user of the software to ensure it stays up-to-date. Perhaps you can add a `brew maintainer needed` in the readme.

**Comment by lfb0801** [comment]
What is the progress on this Issue?
I just went through the installation process on macos and a brew install would have made my life a lot easier 😜 .

**Comment by jaspervdj** [comment]
@lfb0801 I wouldn't mind having this, but I don't have a Mac around.  In the meantime, maybe the [darwin binaries](https://github.com/jaspervdj/patat/releases/tag/v0.8.7.0) would work?  Should I add more explicit instructions on how to install it from the binary release on Mac OS X?

**Comment by lfb0801** [comment]
Well, I installed patat through the darwin binaries you mentioned, but being able to install in through homebrew would have made it much easier. If I have time I might be able to get a fork ready for you. 👍🏻

**Comment by nicholasdille** [comment]
I have created an unofficial formula for `patat` in [my tap](https://github.com/nicholasdille/homebrew-tap). There's two variants:

1. `patat-bin` installs from the official binaries
2. `patat` is a bottled install

Here's how to use it:

```bash
brew tap nicholasdille/tap
brew install patat
```

Feedback is very welcome :-)
