### ISSUE TITLE
slideLevel default is incorrect in README.md, isn't it?

### ISSUE THREAD

**Issue by funkyfuture** [jaspervdj/patat#88]
the `README.md` claims that the `slideLevel` default values is `2`, but i observe the same behaviour with no value set and setting `1`. i did not propose a concrete change because it has implications on the explanation and explanation that follows and i don't want to mess that up.

**Comment by jaspervdj** [comment]
Thanks for letting me know @funkyfuture!

I was not able to reproduce this.  At least for the example, none and `2` produce the same output for me:
```
$ cat slides1.md
---
patat:
  slideLevel: 2
...

# This is a slide

## This is a nested header

This is some content
$ cat slides2.md
# This is a slide

## This is a nested header

This is some content
$ patat --dump slides1.md
~~~title
# This is a slide

----------
## This is a nested header

This is some content
$ patat --dump slides2.md
~~~title
# This is a slide

----------
## This is a nested header

This is some content
```
What is the version you are using?  Or maybe some other issue is preventing `patat` from reading the configuration correctly?
