### ISSUE TITLE
mixing tabs and spaces breaks rendering

### ISSUE THREAD

**Issue by thoastbrot** [jaspervdj/patat#93]
I inserted tabs into the config, which broke the rendering to an extent I thought the settings were broken. Well, they were... 

edited title: it's more of a tabs vs spaces issue...

**Comment by jaspervdj** [comment]
@thoastbrot Thanks for reporting this! Do you still have an example of a config with tabs that's causing confusing or bad results?  That would save me a bunch of time.

**Comment by thoastbrot** [comment]
Sure, check this file (tab before header:, in case github decides to eat it).

---
title: mixing tabs and spaces bad
author: thoastbrot
patat:
    images:
            backend: 'w3m'
            path: '/usr/lib/w3m/w3mimgdisplay'
    theme:
	header: [vividBlue,onDullBlack]
        emph: [dullBlue,italic]
...
# Thats a title

thats some text

---

# fin

**Comment by jaspervdj** [comment]
Interesting, it seems like the YAML is invalid but `patat` is suppressing the error rather than bailing out.  Should be a fairly easy fix.

**Comment by jaspervdj** [comment]
The example will throw an error now, thanks for reporting!
