### ISSUE TITLE
Color specific text?

### ISSUE THREAD

**Issue by isene** [jaspervdj/patat#94]
I am adding a patat converter to my VIM HyperList plugin and need to color specific HyperList elements (like text in brackets [xx], text in parenthesis, etc.). How can I achieve this in patat?

**Comment by jaspervdj** [comment]
I'm not sure if I understood the question correctly.  Currently you can only
theme semantic elements.  The full list is [here](https://github.com/jaspervdj/patat#syntax-highlighting).
An example customizing the `()` and `[]` parts would look like:

```
---
patat:
    theme:
        linkTarget: [vividBlue, onVividBlack, italic]
        linkText: [onDullWhite, vividRed]
...

Hello [world](https://example.com)
```
